title: "B'more on Rails"
description: "B'more on Rails is a community of Baltimore folks who use the Ruby programming language and the Rails application framework."
url: "http://bmoreonrails.github.io"
baseurl: ""

plugins:
  - jekyll-seo-tag

logo: "/images/logo300.png"
twitter:
  card: summary
